import type { Metadata } from "next"
import { PlayerProfileRoute } from "@/components/player-profile-route"
import { findPlayerForMeta, tierLabel } from "@/lib/profile-meta"

// Per-player <title> / description / social card, so a shared /player/<name>
// link unfurls in Discord as the player's name + slogan rather than a generic
// site title. The OG image itself is generated by opengraph-image.tsx alongside
// this file (Next wires it into og:image / twitter:image automatically).
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params
  const player = await findPlayerForMeta(slug)

  if (!player) {
    return {
      title: "Player not found — JK2 Capture the Flag",
      description: "This player profile could not be found.",
    }
  }

  const title = `${player.name} — JK2 Capture the Flag`
  const label = tierLabel(player.tier)
  const description = player.slogan ? `“${player.slogan}” · ${label}` : `${label} · JK2 CTF player profile`

  return {
    title,
    description,
    openGraph: { title, description, type: "profile" },
    twitter: { card: "summary_large_image", title, description },
  }
}

// Shareable player profile URL, e.g. /player/shax. All data is public-readable
// (players / matches / match_stats / player_aliases select-all RLS policies), so
// there is no auth gate — mirrors the public balancer page.
export default async function PlayerPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  return <PlayerProfileRoute slug={slug} />
}
