// GENERATED by scripts/glm-skins.mjs — do not edit by hand.
//
// One entry per model, listing the skins JK2 ships for it and which of its
// surfaces each one repaints. See ModelSkin in lib/player-models.ts for what
// the numbers mean and why they aren't filenames.
//
// Regenerate with every model named in one command:
//   node scripts/glm-skins.mjs --assets <root> \
//     --model kyle \
//     --model reborn \
//     --model shadowtrooper \
//     --model tavion \
//     --model desann \
//     --write lib/model-skins.ts

import type { ModelSkin } from "@/lib/player-models"

export const MODEL_SKINS: Record<string, ModelSkin[]> = {
  kyle: [
    { id: "default", label: "Default", textures: 0, surfaces: {} },
    {
      id: "blue",
      label: "Blue team",
      textures: 3,
      surfaces: { hips: 0, hips_torso: 1, r_leg: 0, l_leg: 0, hips_belt: 2, torso: 1, torso_l_shoulder: 1, torso_r_shoulder: 1, r_arm: 1, r_hand_wrist: 1, l_arm: 1, l_hand_wrist: 1, torso_shoulder_pad: 2, torso_collar: 2 },
    },
    {
      id: "red",
      label: "Red team",
      textures: 3,
      surfaces: { hips: 0, hips_torso: 1, r_leg: 0, l_leg: 0, hips_belt: 2, torso: 1, torso_l_shoulder: 1, torso_r_shoulder: 1, r_arm: 1, r_hand_wrist: 1, l_arm: 1, l_hand_wrist: 1, torso_shoulder_pad: 2, torso_collar: 2 },
    },
  ],
  reborn: [
    { id: "default", label: "Default", textures: 0, surfaces: {} },
    {
      id: "acrobat",
      label: "Acrobat",
      textures: 8,
      surfaces: { hips: 0, hips_torso: 1, torso: 1, torso_l_shoulder: 1, torso_r_shoulder: 1, r_arm: 1, r_hand: 2, r_hand_wrist: 1, l_arm: 1, l_hand: 2, l_hand_wrist: 1, head: 3, head_face: 4, head_eyes_mouth: 5, torso_cowelbase: 3, l_leg: 6, r_leg: 6, hips_flaps: 7 },
    },
    {
      id: "blue",
      label: "Blue team",
      textures: 8,
      surfaces: { hips: 0, hips_torso: 1, torso: 1, torso_l_shoulder: 1, torso_r_shoulder: 1, r_arm: 1, r_hand: 2, r_hand_wrist: 1, l_arm: 1, l_hand: 2, l_hand_wrist: 1, head: 3, head_face: 4, head_eyes_mouth: 5, torso_cowelbase: 3, l_leg: 6, r_leg: 6, hips_flaps: 7 },
    },
    {
      id: "boss",
      label: "Boss",
      textures: 8,
      surfaces: { hips: 0, hips_torso: 1, torso: 1, torso_l_shoulder: 1, torso_r_shoulder: 1, r_arm: 1, r_hand: 2, r_hand_wrist: 1, l_arm: 1, l_hand: 2, l_hand_wrist: 1, head: 3, head_face: 4, head_eyes_mouth: 5, torso_cowelbase: 3, l_leg: 6, r_leg: 6, hips_flaps: 7 },
    },
    {
      id: "fencer",
      label: "Fencer",
      textures: 8,
      surfaces: { hips: 0, hips_torso: 1, torso: 1, torso_l_shoulder: 1, torso_r_shoulder: 1, r_arm: 1, r_hand: 2, r_hand_wrist: 1, l_arm: 1, l_hand: 2, l_hand_wrist: 1, head: 3, head_face: 4, head_eyes_mouth: 5, torso_cowelbase: 3, l_leg: 6, r_leg: 6, hips_flaps: 7 },
    },
    {
      id: "forceuser",
      label: "Forceuser",
      textures: 8,
      surfaces: { hips: 0, hips_torso: 1, torso: 1, torso_l_shoulder: 1, torso_r_shoulder: 1, r_arm: 1, r_hand: 2, r_hand_wrist: 1, l_arm: 1, l_hand: 2, l_hand_wrist: 1, head: 3, head_face: 4, head_eyes_mouth: 5, torso_cowelbase: 3, l_leg: 6, r_leg: 6, hips_flaps: 7 },
    },
    {
      id: "red",
      label: "Red team",
      textures: 8,
      surfaces: { hips: 0, hips_torso: 1, torso: 1, torso_l_shoulder: 1, torso_r_shoulder: 1, r_arm: 1, r_hand: 2, r_hand_wrist: 1, l_arm: 1, l_hand: 2, l_hand_wrist: 1, head: 3, head_face: 4, head_eyes_mouth: 5, torso_cowelbase: 3, l_leg: 6, r_leg: 6, hips_flaps: 7 },
    },
  ],
  shadowtrooper: [
    { id: "default", label: "Default", textures: 0, surfaces: {} },
    {
      id: "blue",
      label: "Blue team",
      textures: 4,
      surfaces: { hips: 0, l_leg: 0, r_leg: 0, hips_torso: 1, torso: 1, r_arm: 1, r_hand: 2, r_hand_wrist: 1, l_arm: 1, l_hand: 2, l_hand_wrist: 1, head: 3 },
    },
    {
      id: "red",
      label: "Red team",
      textures: 4,
      surfaces: { hips: 0, l_leg: 0, r_leg: 0, hips_torso: 1, torso: 1, r_arm: 1, r_hand: 2, r_hand_wrist: 1, l_arm: 1, l_hand: 2, l_hand_wrist: 1, head: 3 },
    },
  ],
  tavion: [
    { id: "default", label: "Default", textures: 0, surfaces: {} },
    {
      id: "blue",
      label: "Blue team",
      textures: 2,
      surfaces: { hips: 0, l_leg: 0, r_leg: 0, torso: 1, l_arm: 1, r_arm: 1 },
    },
    {
      id: "red",
      label: "Red team",
      textures: 2,
      surfaces: { hips: 0, l_leg: 0, r_leg: 0, torso: 1, l_arm: 1, r_arm: 1 },
    },
  ],
  desann: [
    { id: "default", label: "Default", textures: 0, surfaces: {} },
    {
      id: "blue",
      label: "Blue team",
      textures: 3,
      surfaces: { hips: 0, l_leg: 0, r_leg: 0, torso: 1, l_arm: 1, r_arm: 1, r_arm_pad: 2, torso_armor: 2, hips_armor: 2 },
    },
    {
      id: "red",
      label: "Red team",
      textures: 3,
      surfaces: { hips: 0, l_leg: 0, r_leg: 0, torso: 1, l_arm: 1, r_arm: 1, r_arm_pad: 2, torso_armor: 2, hips_armor: 2 },
    },
  ],
}
