// Catalogue of JK2 player models available to the 3D profile viewer.
//
// This list is the security boundary for model asset access. /api/model-url will
// only mint a signed URL for a `file` that appears here, so neither a crafted
// request nor a bad value in players.model can be turned into a reference to
// some other object in the storage bucket. Adding a model means adding a row
// here — there is deliberately no way to request an arbitrary path.
//
// Converted with docs/jk2-model-conversion.md. The .glb files are NOT in this
// repo: they're Raven/Activision assets and this repo is public, so they live in
// a private Supabase Storage bucket instead (see MODEL_BUCKET below).

import { MODEL_SKINS } from "@/lib/model-skins"

export const MODEL_BUCKET = "models"

/**
 * How long a minted signed URL stays valid — and, at half this, how long the
 * browser may reuse the /api/model-url response that carries it. An hour
 * because the URL doubles as the browser's cache key for a ~2 MB .glb: every
 * fresh mint is a full re-download, so short TTLs made each revisit pay the
 * whole download again. A scraped link still dies within the hour.
 */
export const MODEL_URL_TTL_SECONDS = 3600

/** The skin every model is exported wearing, and the one baked into its .glb. */
export const DEFAULT_SKIN = "default"

/**
 * One of a model's `.skin` files, reduced to what the viewer needs.
 *
 * JK2 ships a model as one mesh plus several `.skin` files — plain lists of
 * `surface,texturepath` — so Kyle's red team look is his default with three
 * images swapped, not a second model. The viewer does the same thing: it loads
 * the one `.glb` and overlays the handful of textures that differ.
 *
 * `surfaces` maps a surface name to a slot number rather than a filename.
 * Filenames would be Raven's, and this file is in a public repo; a slot index
 * tells the viewer everything it needs and discloses nothing. Both halves are
 * generated by scripts/glm-skins.mjs, which reads the game's own `.skin` files
 * and diffs them — so the mapping is the game's, not a guess at it.
 */
export type ModelSkin = {
  /** Stored in the loadout and used in API requests. */
  id: string
  /** Shown in the picker. */
  label: string
  /** How many replacement textures this skin ships. Zero for the default. */
  textures: number
  /** Surface name → texture slot. Empty for the default: it's already in the .glb. */
  surfaces: Record<string, number>
  /**
   * File extension per texture slot, when it isn't "jpg". Only set for a slot
   * whose surface is alpha-tested in the model's default material (see
   * scripts/glm-graft.mjs's analyseShader) — a JPEG has no alpha channel, so
   * swapping to one would silently undo the cutout. Absent entirely for every
   * skin that doesn't need it, which is all of them except Bones' red/blue.
   */
  formats?: string[]
  /**
   * Slots drawn additively instead of as a diffuse repaint. A JK2 skin can
   * point a surface at a pure `blendFunc GL_ONE GL_ONE` shader — no opaque
   * base at all, invisible where the texture is dark and glowing where it's
   * bright. Andromeda's team skins do this to her entire right arm, and that
   * translucent energy limb is the model's signature look. A texture swap on
   * the existing opaque material can't express it, so the viewer rebuilds
   * these slots as additive emissive materials — see components/model-skin.tsx.
   */
  additive?: number[]
}

export type PlayerModel = {
  /** Stored in players.model and used in API requests. */
  id: string
  /** Shown in the profile editor's picker. */
  label: string
  /** Object name inside the storage bucket. */
  file: string
  /** Skins this model can wear, default first. */
  skins: ModelSkin[]
  /** Author credit for fan-made models, shown alongside the label in the picker. */
  credit?: string
}

/** Every model has a default; the variants come from the generated catalogue. */
const PLAIN_SKINS: ModelSkin[] = [{ id: DEFAULT_SKIN, label: "Default", textures: 0, surfaces: {} }]

function skinsFor(id: string): ModelSkin[] {
  return MODEL_SKINS[id] ?? PLAIN_SKINS
}

// Kyle came through Blender; the rest were grafted onto his skeleton by
// scripts/glm-graft.mjs, which is why they all animate identically — they are
// literally driven by the same clips.
export const PLAYER_MODELS: PlayerModel[] = [
  {
    id: "kyle",
    label: "Kyle Katarn",
    file: "kyle.glb",
    skins: skinsFor("kyle"),
  },
  {
    id: "reborn",
    label: "Reborn",
    file: "reborn.glb",
    skins: skinsFor("reborn"),
  },
  {
    id: "shadowtrooper",
    label: "Shadowtrooper",
    file: "shadowtrooper.glb",
    skins: skinsFor("shadowtrooper"),
  },
  {
    id: "tavion",
    label: "Tavion",
    file: "tavion.glb",
    skins: skinsFor("tavion"),
  },
  {
    id: "desann",
    label: "Desann",
    file: "desann.glb",
    // Worth knowing before anyone reports it as a bug: the viewer normalises
    // every model to the same height, so he doesn't tower here the way he does
    // in game.
    skins: skinsFor("desann"),
  },
  {
    id: "luke",
    label: "Luke Skywalker",
    file: "luke.glb",
    skins: skinsFor("luke"),
  },
  {
    id: "jan",
    label: "Jan Ors",
    file: "jan.glb",
    skins: skinsFor("jan"),
  },
  {
    id: "lando",
    label: "Lando Calrissian",
    file: "lando.glb",
    skins: skinsFor("lando"),
  },
  {
    id: "jedi",
    label: "Jedi",
    file: "jedi.glb",
    skins: skinsFor("jedi"),
  },
  {
    id: "stormtrooper",
    label: "Stormtrooper",
    file: "stormtrooper.glb",
    skins: skinsFor("stormtrooper"),
  },
  {
    id: "swamptrooper",
    label: "Swamptrooper",
    file: "swamptrooper.glb",
    skins: skinsFor("swamptrooper"),
  },
  {
    id: "imperial",
    label: "Imperial Officer",
    file: "imperial.glb",
    skins: skinsFor("imperial"),
  },
  {
    id: "rebel",
    label: "Rebel Trooper",
    file: "rebel.glb",
    skins: skinsFor("rebel"),
  },
  {
    id: "jeditrainer",
    label: "Jedi Trainer",
    file: "jeditrainer.glb",
    skins: skinsFor("jeditrainer"),
  },
  // Fan-made models, grafted the same way as the roster above. Only added once
  // their .glm actually declares the shared 72-bone _humanoid skeleton — several
  // others Sam sent (rayman, x_Eternal, cal_kestis) use a different, incompatible
  // bone layout and were left out; see docs/jk2-model-conversion.md §7.8.
  {
    id: "andromeda",
    label: "Andromeda",
    file: "andromeda.glb",
    skins: skinsFor("andromeda"),
    credit: "FetchD",
  },
  {
    id: "bones",
    label: "Bones",
    file: "bones.glb",
    skins: skinsFor("bones"),
  },
  {
    id: "horseton",
    label: "Horseton",
    file: "horseton.glb",
    skins: skinsFor("horseton"),
    credit: "Booti",
  },
  // Stock JK2, not fan-made — just never converted alongside the rest of the
  // base roster above. Its "Shadow" skin is a fan retexture (zzz_Crash.pk3,
  // internally named ShadowRodian) that turned out to share Rodian's exact
  // surface layout, so it's a skin variant rather than a second model.
  {
    id: "rodian",
    label: "Rodian",
    file: "rodian.glb",
    skins: skinsFor("rodian"),
  },
]

/**
 * Object name in the bucket for every skin texture any model can ask for.
 *
 * Derived from PLAYER_MODELS rather than typed out, for the same reason
 * PROP_ASSETS derives from SABER_COLOURS: a skin can't reach the picker without
 * its files becoming resolvable, and can't be retired while leaving a dangling
 * entry behind. Ids are built from the model, skin and slot, so nothing a caller
 * sends is ever concatenated into a path.
 */
export const SKIN_ASSETS: Record<string, string> = Object.fromEntries(
  PLAYER_MODELS.flatMap((model) =>
    model.skins.flatMap((skin) =>
      Array.from({ length: skin.textures }, (_, slot) => [
        skinTextureAsset(model.id, skin.id, slot),
        `skins/${model.id}/${skin.id}/${slot}.${skin.formats?.[slot] ?? "jpg"}`,
      ]),
    ),
  ),
)

/** Asset id for one replacement texture of a model's skin. */
export function skinTextureAsset(modelId: string, skinId: string, slot: number): string {
  return `skin-${modelId}-${skinId}-${slot}`
}

/** Every texture id a skin needs, in slot order. Empty for the default. */
export function skinAssetIds(modelId: string, skin: ModelSkin): string[] {
  return Array.from({ length: skin.textures }, (_, slot) => skinTextureAsset(modelId, skin.id, slot))
}

export function findSkinAsset(id: string | null | undefined): string | null {
  if (!id) return null
  return SKIN_ASSETS[id] ?? null
}

export function findPlayerModel(id: string | null | undefined): PlayerModel | null {
  if (!id) return null
  return PLAYER_MODELS.find((m) => m.id === id) ?? null
}

/**
 * A model's skin by id, or null for the default and for anything unrecognised.
 *
 * Null covers both cases on purpose: the default needs no override, and a skin
 * id left over from a retired model should leave a profile rendering the plain
 * model rather than erroring.
 */
export function findModelSkin(model: PlayerModel | null, skinId: string | null | undefined): ModelSkin | null {
  if (!model || !skinId || skinId === DEFAULT_SKIN) return null
  return model.skins.find((skin) => skin.id === skinId && skin.textures > 0) ?? null
}

/** Whether a stored value still corresponds to a model we ship. Retiring a model
 *  should leave old profiles rendering nothing, not erroring. */
export function isKnownModel(id: string | null | undefined): boolean {
  return findPlayerModel(id) !== null
}
