// Catalogue of JK2 player models available to the 3D profile viewer.
//
// This list is the security boundary for model asset access. /api/model-url will
// only mint a signed URL for a `file` that appears here, so neither a crafted
// request nor a bad value in players.model can be turned into a reference to
// some other object in the storage bucket. Adding a model means adding a row
// here — there is deliberately no way to request an arbitrary path.
//
// Converted with docs/jk2-model-conversion.md. The .glb files are NOT in this
// repo: they're Raven/Activision assets and this repo is public, so they live in
// a private Supabase Storage bucket instead (see MODEL_BUCKET below).

import { MODEL_SKINS } from "@/lib/model-skins"

export const MODEL_BUCKET = "models"

/** How long a minted signed URL stays valid. Long enough to load, short enough
 *  that a scraped link is worthless within the hour. */
export const MODEL_URL_TTL_SECONDS = 600

/** The skin every model is exported wearing, and the one baked into its .glb. */
export const DEFAULT_SKIN = "default"

/**
 * One of a model's `.skin` files, reduced to what the viewer needs.
 *
 * JK2 ships a model as one mesh plus several `.skin` files — plain lists of
 * `surface,texturepath` — so Kyle's red team look is his default with three
 * images swapped, not a second model. The viewer does the same thing: it loads
 * the one `.glb` and overlays the handful of textures that differ.
 *
 * `surfaces` maps a surface name to a slot number rather than a filename.
 * Filenames would be Raven's, and this file is in a public repo; a slot index
 * tells the viewer everything it needs and discloses nothing. Both halves are
 * generated by scripts/glm-skins.mjs, which reads the game's own `.skin` files
 * and diffs them — so the mapping is the game's, not a guess at it.
 */
export type ModelSkin = {
  /** Stored in the loadout and used in API requests. */
  id: string
  /** Shown in the picker. */
  label: string
  /** How many replacement textures this skin ships. Zero for the default. */
  textures: number
  /** Surface name → texture slot. Empty for the default: it's already in the .glb. */
  surfaces: Record<string, number>
}

export type PlayerModel = {
  /** Stored in players.model and used in API requests. */
  id: string
  /** Shown in the profile editor's picker. */
  label: string
  /** Object name inside the storage bucket. */
  file: string
  /** Roughly how the model reads, for the picker. */
  blurb?: string
  /** Skins this model can wear, default first. */
  skins: ModelSkin[]
}

/** Every model has a default; the variants come from the generated catalogue. */
const PLAIN_SKINS: ModelSkin[] = [{ id: DEFAULT_SKIN, label: "Default", textures: 0, surfaces: {} }]

function skinsFor(id: string): ModelSkin[] {
  return MODEL_SKINS[id] ?? PLAIN_SKINS
}

// Kyle came through Blender; the rest were grafted onto his skeleton by
// scripts/glm-graft.mjs, which is why they all animate identically — they are
// literally driven by the same clips.
export const PLAYER_MODELS: PlayerModel[] = [
  {
    id: "kyle",
    label: "Kyle Katarn",
    file: "kyle.glb",
    blurb: "The stock JK2 protagonist",
    skins: skinsFor("kyle"),
  },
  {
    id: "reborn",
    label: "Reborn",
    file: "reborn.glb",
    blurb: "Hooded Sith apprentice — six skins, the most on the disc",
    skins: skinsFor("reborn"),
  },
  {
    id: "shadowtrooper",
    label: "Shadowtrooper",
    file: "shadowtrooper.glb",
    blurb: "Cortosis-armoured stormtrooper with a saber",
    skins: skinsFor("shadowtrooper"),
  },
  {
    id: "tavion",
    label: "Tavion",
    file: "tavion.glb",
    blurb: "Desann's apprentice",
    skins: skinsFor("tavion"),
  },
  {
    id: "desann",
    label: "Desann",
    file: "desann.glb",
    // Worth knowing before anyone reports it as a bug: the viewer normalises
    // every model to the same height, so he doesn't tower here the way he does
    // in game.
    blurb: "The fallen Jedi — huge in game, same height as everyone here",
    skins: skinsFor("desann"),
  },
]

/**
 * Object name in the bucket for every skin texture any model can ask for.
 *
 * Derived from PLAYER_MODELS rather than typed out, for the same reason
 * PROP_ASSETS derives from SABER_COLOURS: a skin can't reach the picker without
 * its files becoming resolvable, and can't be retired while leaving a dangling
 * entry behind. Ids are built from the model, skin and slot, so nothing a caller
 * sends is ever concatenated into a path.
 */
export const SKIN_ASSETS: Record<string, string> = Object.fromEntries(
  PLAYER_MODELS.flatMap((model) =>
    model.skins.flatMap((skin) =>
      Array.from({ length: skin.textures }, (_, slot) => [
        skinTextureAsset(model.id, skin.id, slot),
        `skins/${model.id}/${skin.id}/${slot}.jpg`,
      ]),
    ),
  ),
)

/** Asset id for one replacement texture of a model's skin. */
export function skinTextureAsset(modelId: string, skinId: string, slot: number): string {
  return `skin-${modelId}-${skinId}-${slot}`
}

/** Every texture id a skin needs, in slot order. Empty for the default. */
export function skinAssetIds(modelId: string, skin: ModelSkin): string[] {
  return Array.from({ length: skin.textures }, (_, slot) => skinTextureAsset(modelId, skin.id, slot))
}

export function findSkinAsset(id: string | null | undefined): string | null {
  if (!id) return null
  return SKIN_ASSETS[id] ?? null
}

export function findPlayerModel(id: string | null | undefined): PlayerModel | null {
  if (!id) return null
  return PLAYER_MODELS.find((m) => m.id === id) ?? null
}

/**
 * A model's skin by id, or null for the default and for anything unrecognised.
 *
 * Null covers both cases on purpose: the default needs no override, and a skin
 * id left over from a retired model should leave a profile rendering the plain
 * model rather than erroring.
 */
export function findModelSkin(model: PlayerModel | null, skinId: string | null | undefined): ModelSkin | null {
  if (!model || !skinId || skinId === DEFAULT_SKIN) return null
  return model.skins.find((skin) => skin.id === skinId && skin.textures > 0) ?? null
}

/** Whether a stored value still corresponds to a model we ship. Retiring a model
 *  should leave old profiles rendering nothing, not erroring. */
export function isKnownModel(id: string | null | undefined): boolean {
  return findPlayerModel(id) !== null
}
